### ISSUE TITLE
Localization by template languages/custom-wp-login.pot

### ISSUE THREAD

**Issue by davidemerlitti** [yikesinc/yikes-inc-custom-login#14]
I tried to add a new language file (it_IT) by hand and by using the "Loco Translate" plugin. Everything seems to be ok ma the texts are displayed only in their original language.
The language files in the "languages" directory are the following:

custom-wp-login-it_IT.mo
custom-wp-login-it_IT.po
custom-wp-login.pot

The pages are not cached and "Loco Translate" plugin works perfectly with the other plugins.
The Text Domain and Domain Path of YIKES Custom Login are ok:

Text Domain:       custom-wp-login
Domain Path:		  /languages

I don't understand what the problem is. Any help would be appreciated
Thanks

**Comment by TheTracyL** [comment]
Hello @davidemerlitti 

You need to translate this plugin via GlotPress: https://translate.wordpress.org/projects/wp-plugins/custom-wp-login/

Language packs replaced pot files a while ago.

Thank you!
-Tracy

**Comment by davidemerlitti** [comment]
Hi @TheTracyL 

thank you for your prompt reply. I am disappointed to know that language packs replaced pot files.
For my project I need to translate in italian just a few strings for the frontend (for sign-in e forgot password pages) and I don't have time to translate the 95% of the strings to get the language pack.

I have to find a quick and dirty/workaround.

Best regards

-- 
Davide

**Comment by freddiemixell** [comment]
@davidemerlitti,

Try the Loco Translate plugin. We recommend that for customers who want to translate just a few strings in WooCommerce Subscriptions and other WC extensions.

https://wordpress.org/plugins/loco-translate/

**Comment by davidemerlitti** [comment]
Hi @freddiemixell,

have you read my first message at the top? <<and by using the "Loco Translate" plugin>>. It does not work with custom wp login.

**Comment by davidemerlitti** [comment]
I think that the reason the po/mo based localization does not work with this plugin is that there's a bug in the class YIKES_Custom_Login_i18n ("file custom-wp-login/lib/classes/i18n.php"). This is a simple fix:

```
public function load_plugin_textdomain() {
  load_plugin_textdomain(
    'custom-wp-login',
    false,
    /*YIKES_CUSTOM_LOGIN_PATH . */ 'custom-wp-login/languages/'
    );
}
```
