### ISSUE TITLE
YIKES_Custom_Login::register_settings_fields method does not exist

### ISSUE THREAD

**Issue by ramiabraham** [yikesinc/yikes-inc-custom-login#2]
Looks like the noted method is missing in the primary class, called here:

`https://github.com/yikesinc/yikes-inc-custom-login/blob/master/yikes-inc-custom-login.php#L57`

(Love this btw, nice to see an all-in-one solution for front-end login flows).

**Comment by EvanHerman** [comment]
Hey @ramiabraham,

Thanks for catching that! I just patched the issue in the latest commit. We will be continuing to build this out, and ideally will be releasing this into the WordPress repository - so feel free to check back often for updates.

Thanks again!
Evan
