### ISSUE TITLE
How to translate this plugin

### ISSUE THREAD

**Issue by Julianojc** [yikesinc/yikes-inc-custom-login#4]
is possible?

**Comment by kpu23** [comment]
Hello Julianojc,

Thank you for bringing this to our attention. Unfortunately, the plugin is not currently setup for GlotPress translations _but_ we will work on it and let you know when it is ready. We're hoping to have it updated within a week or two. 

Thanks for the question.

**Comment by kpu23** [comment]
Hello Julianojc,

We've made updates to this plugin and translations are now possible! Check out the [GlotPress page for this plugin](https://translate.wordpress.org/projects/wp-plugins/custom-wp-login) to start adding translation files. 

If you're enjoying the plugin and support, please consider leaving a review: https://wordpress.org/support/plugin/custom-wp-login/reviews/

It would bring a smile to the plugin (and its developers!) 

Cheers,
Kevin.
